#!/bin/sh

echo "\nRunning pre-commit checks...\n"

echo "\nBuilding the application"
yarn run build

echo "\nRunning linters"
yarn run lint

echo "\nFixing lint errors"
yarn run lintFix

echo "\nRunning tests"
yarn run test